import { useMemo } from 'react';
import { useAdminStockModel } from '../AdminStockModelContext';

export function useAdminStockImportsModule() {
  const model = useAdminStockModel();

  return useMemo(
    () => ({
      t: model.t,
      systems: model.systems,
      importStep: model.importStep,
      provisionMode: model.provisionMode,
      handleProvisionModeChange: model.handleProvisionModeChange,
      importSystemId: model.importSystemId,
      handleImportSystemChange: model.handleImportSystemChange,
      importWarehouseCode: model.importWarehouseCode,
      setImportWarehouseCode: model.setImportWarehouseCode,
      selectedImportSystem: model.selectedImportSystem,
      requiredIdentifiersPerDevice: model.requiredIdentifiersPerDevice,
      selectedImportIdentifierLabel: model.selectedImportIdentifierLabel,
      manualMacAddress: model.manualMacAddress,
      setManualMacAddress: model.setManualMacAddress,
      manualIdentifierInput: model.manualIdentifierInput,
      setManualIdentifierInput: model.setManualIdentifierInput,
      normalizePhysicalIdentifierInput: model.normalizePhysicalIdentifierInput,
      manualIdentifiers: model.manualIdentifiers,
      setManualIdentifiers: model.setManualIdentifiers,
      handleAddManualIdentifier: model.handleAddManualIdentifier,
      handleRemoveManualIdentifier: model.handleRemoveManualIdentifier,
      manualBatchDevices: model.manualBatchDevices,
      handleAddManualDevice: model.handleAddManualDevice,
      handleRemoveManualDevice: model.handleRemoveManualDevice,
      importRawInput: model.importRawInput,
      setImportRawInput: model.setImportRawInput,
      handleImportFile: model.handleImportFile,
      draftRows: model.draftRows,
      importValidation: model.importValidation,
      importIssuesPreview: model.importIssuesPreview,
      validateImportMutation: model.validateImportMutation,
      createDevicesMutation: model.createDevicesMutation,
      handleVerifyImport: model.handleVerifyImport,
      handleConfirmImport: model.handleConfirmImport,
      resetProvisionDraft: model.resetProvisionDraft,
      extensionProvisionMode: model.extensionProvisionMode,
      handleExtensionProvisionModeChange: model.handleExtensionProvisionModeChange,
      extensionSystemId: model.extensionSystemId,
      handleExtensionSystemChange: model.handleExtensionSystemChange,
      extensionCapableSystems: model.extensionCapableSystems,
      extensionWarehouseCode: model.extensionWarehouseCode,
      setExtensionWarehouseCode: model.setExtensionWarehouseCode,
      selectedExtensionSystem: model.selectedExtensionSystem,
      selectedExtensionIdentifierLabel: model.selectedExtensionIdentifierLabel,
      manualExtensionInput: model.manualExtensionInput,
      setManualExtensionInput: model.setManualExtensionInput,
      handleAddManualExtension: model.handleAddManualExtension,
      handleRemoveManualExtension: model.handleRemoveManualExtension,
      manualExtensionBatch: model.manualExtensionBatch,
      handleExtensionImportFile: model.handleExtensionImportFile,
      extensionRawInput: model.extensionRawInput,
      setExtensionRawInput: model.setExtensionRawInput,
      extensionDraftIdentifiers: model.extensionDraftIdentifiers,
      duplicateExtensionIdentifiers: model.duplicateExtensionIdentifiers,
      invalidExtensionIdentifiers: model.invalidExtensionIdentifiers,
      readyExtensionCount: model.readyExtensionCount,
      createExtensionsMutation: model.createExtensionsMutation,
      handleConfirmExtensions: model.handleConfirmExtensions,
      resetExtensionDraft: model.resetExtensionDraft,
    }),
    [model],
  );
}
